/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.p2.TRAB2.Associacoes;

import com.p2.TRAB1.normais.Coordenador;
import com.p2.TRAB1.normais.SecAcademica;
import com.p2.TRAB1.normais.SecFinanceira;
import com.p2.TRAB2.Menu1;
import com.p2.TRAB2.Models.CoordenadorModel;
import com.p2.TRAB2.Models.SecAModel;
import com.p2.TRAB2.Models.SecFModel;


public class AFaculdade extends javax.swing.JFrame {
    
    public final CoordenadorModel modelCoordenador = new CoordenadorModel();
    public final SecAModel modelSA = new SecAModel();
    public final SecFModel modelSF = new SecFModel();
    /**
     * Creates new form AFaculdade
     */
    public AFaculdade() {
        initComponents();
        this.setLocationRelativeTo(null);

        comboxA.setModel(modelSA);
        comboxF.setModel(modelSF);
        comboxC.setModel(modelCoordenador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cordR = new javax.swing.JRadioButton();
        SFR = new javax.swing.JRadioButton();
        comboxF = new javax.swing.JComboBox<>();
        comboxC = new javax.swing.JComboBox<>();
        SAR = new javax.swing.JRadioButton();
        comboxA = new javax.swing.JComboBox<>();
        associaBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cordR.setText("Coordenador:");
        cordR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cordRActionPerformed(evt);
            }
        });

        SFR.setText("Sec Financeiro:");
        SFR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SFRActionPerformed(evt);
            }
        });

        comboxF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboxC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxCActionPerformed(evt);
            }
        });

        SAR.setText("Sec Academicos:");
        SAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SARActionPerformed(evt);
            }
        });

        comboxA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        associaBTN.setText("Associar");
        associaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associaBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cordR)
                            .addComponent(comboxC, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SFR)
                            .addComponent(comboxF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboxA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SAR))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(associaBTN)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cordR)
                    .addComponent(SFR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboxF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboxC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboxA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(associaBTN)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SARActionPerformed
        if(SAR.isSelected()){
            comboxA.setEnabled(true);
        }else{
            comboxA.setEnabled(false);
        }
    }//GEN-LAST:event_SARActionPerformed

    private void cordRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cordRActionPerformed
        if(cordR.isSelected()){
            comboxC.setEnabled(true);
        }else{
            comboxC.setEnabled(false);
        }
    }//GEN-LAST:event_cordRActionPerformed

    private void SFRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SFRActionPerformed
        if(SFR.isSelected()){
            comboxF.setEnabled(true);
        }else{
            comboxF.setEnabled(false);
        }
    }//GEN-LAST:event_SFRActionPerformed

    private void associaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associaBTNActionPerformed
        if(comboxC.isEnabled()){
            
            Menu1.faculdades.get(0).setCoordenadores((Coordenador) comboxC.getSelectedItem());
        }
        if(comboxF.isEnabled()){
            Menu1.faculdades.get(0).setSecretariosFinanceiros((SecFinanceira) comboxF.getSelectedItem());
        }
        if(comboxA.isEnabled()){
            Menu1.faculdades.get(0).setSecretariosAcademicos((SecAcademica) comboxA.getSelectedItem());
        }
        this.dispose();
    }//GEN-LAST:event_associaBTNActionPerformed

    private void comboxCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AFaculdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AFaculdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AFaculdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AFaculdade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AFaculdade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton SAR;
    private javax.swing.JRadioButton SFR;
    private javax.swing.JButton associaBTN;
    private javax.swing.JComboBox<String> comboxA;
    private javax.swing.JComboBox<String> comboxC;
    private javax.swing.JComboBox<String> comboxF;
    private javax.swing.JRadioButton cordR;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
